### ISSUE TITLE
Stops Responding & Restarting Live Stream gives Blender Py Error:

### ISSUE THREAD

**Issue by SkywolfGameStudios** [Viga-Entertainment-Technology/Unreal-LiveLink-for-Blender#1]
Hey Viga Team,

Pretty cool idea for an addon and plugin which has alot of interesting potential. I tried it the first time yesterday, it didn't work then tried it again this morning as a second attempt today to give it another chance and got it partially working so I'll update my review on the UE Marketplace to correct it but honestly it definitely needs a lot of TLC to get it going further. 

This is pretty good stuff for a starting point but I ran into another Issue. The syncing seems to break after a short while even though everything is enabled and I am unable to restart the Live Link from the Blender Addon. I have to trash the livelink in ue and readd it as well as close blender and reopen it to work around that problem just to get it working again (very annoying).

In Blender I get this error:
Python: Traceback (most recent call last):
  File "C:\Users\Deygu\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderLiveLinkAddon.py", line 174, in modal
    for i in bpy.data.objects[mytool.my_string].pose.bones:
KeyError: 'bpy_prop_collection[key]: key "" not found'

location: <unknown location>:-1

![image](https://user-images.githubusercontent.com/33204341/164043365-bf7d9f27-6d77-4910-a29d-5484e4ad689c.png)

~ Kade (Deygus)
Skywolf Game Studios

**Comment by shreyaschincholkar** [comment]
Thank you for taking the time to give us your valuable feedback. We will resolve this issue as soon as possible.

**Comment by SkywolfGameStudios** [comment]
> Thank you for taking the time to give us your valuable feedback. We will resolve this issue as soon as possible.

You are welcome and thank you for the response and looking into it.

**Comment by MehtaSarthak** [comment]
> > Thank you for taking the time to give us your valuable feedback. We will resolve this issue as soon as possible.
> 
> You are welcome and thank you for the response and looking into it.

Hi @SkywolfGameStudios , we have updated the live link addon you can check now.
